name: Qodana

on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ "master" ]

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - run: sudo df -h
      - name: 'Qodana Scan'
        uses: JetBrains/qodana-action@v2022.3.0
        with:
          args: --baseline,.qodana/baseline.sarif.json
          pr-mode: false
      - run: sudo df -h
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json
